// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okurysbomlqejukvdwct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rdXJ5c2JvbWxxZWp1a3Zkd2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDUwMTYsImV4cCI6MjA2NDg4MTAxNn0._2KuF_tA_0cnXRxauhlEZR4Xps-gUBcXSwTrYhEpd0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);